variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  name: 'BuildApp'
  inputs:
    command: 'build'
    workingDirectory: 'Azuretests'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'publish'
    publishLocation: 'Container'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'dotnet-sc'
    appType: 'webAppLinux'
    appName: $(appname)
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
